project:  # Project specific configuration section
  # Project name, used as s3 key prefix when uploading objects
  name:  aws-refarch-moodle
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    BastionInstanceType: t2.nano
    CachePrefix: 'ccle'
    CloudFrontAcmCertificate: ''
    DatabaseCmk: 'arn:aws:kms:us-west-2:095974944794:key/dcd37fd9-8fbf-4342-81a8-548681df5ffa'
    DatabaseEncrpytedBoolean: 'true'
    DatabaseInstanceType: 'db.r5.large'
    DomainName: ''
    EC2KeyName: CCLE-DR
    EfsCmk: 'arn:aws:kms:us-west-2:095974944794:key/80ef0149-36fc-4319-b99d-c876d68335fd'
    EfsEncrpytedBoolean: 'true'
    HostedZoneName: ''
    NumberOfAZs: 2
    # PrivateSubnets: 'subnet-06a3baa880629ed73,subnet-0a64f75573465a5d7'
    PublicAlbAcmCertificate: ''
    # PublicSubnets: 'subnet-0768522309f73972a,subnet-0e7454b0142913b70'
    UseRoute53Boolean: false
    UseApplicationCacheBoolean: 'true'
    UseCloudFrontBoolean: 'true'
    UseRoute53Boolean: 'false'
    UseSessionCacheBoolean: 'false'
    # VpcId: 'vpc-0017b23ff4df82e53'
    WebAsgMax: 4
    WebInstanceType: c5.xlarge
  regions: # List of AWS regions
    - us-west-2
  # Name of S3 bucket to upload project to
  s3_bucket: cat-ccle-aws-refarch-moodle
  # ACL for uploaded s3 objects, defaults to 'private'
  s3_object_acl: public-read
  tags:  # Tags to apply to CloudFormation template
    MyTagKey: ccle-dr
  # Path to template file relative to the project config file path. If
  # defined, template is optional in tests
  template: ./templates/00-master.yaml
tests:  # Test definition section
  test:
    # Parameter key-values to pass to CloudFormation, override parameters
    # provided in project section
    parameters:
      ApplicationCacheNodeType: cache.t3.micro
      CachePrefix: 'ccle-test'
      DatabaseInstanceType: db.r5.large
      EfsGrowthInstanceType: t3.micro
      PrivateSubnets: 'subnet-01d8a7092b87ff57b,subnet-0d39c760e52360242'
      PublicSubnets: 'subnet-02fb2e17a34aa3552,subnet-07cf697d8edc81669'
      UseApplicationCacheBoolean: 'false'
      UseSessionCacheBoolean: 'false'
      VpcId: 'vpc-08c23a8a235ced46f'
      WebAsgMax: 1
      WebInstanceType: t3.micro
    # List of AWS regions, will override any regions defined in project
    regions:
      - us-west-2
    s3_bucket: cat-ccle-aws-refarch-moodle-test
    tags:  # Tags to apply to CloudFormation template
      MyTagKey: ccle-dr-test
