project:  # Project specific configuration section
  # Project name, used as s3 key prefix when uploading objects
  name:  aws-refarch-moodle
  parameters:
    AvailabilityZones: us-west-2a,us-west-2b
    CloudFrontAcmCertificate: ''
    DatabaseCmk: ''
    DatabaseEncrpytedBoolean: 'true'
    DomainName: ''
    EC2KeyName: CCLE-DR
    EfsCmk: ''
    EfsEncrpytedBoolean: 'true'
    HostedZoneName: ''
    NumberOfAZs: 2
    PublicAlbAcmCertificate: ''
    UseRoute53Boolean: false
    UseApplicationCacheBoolean: 'true'
    UseCloudFrontBoolean: 'true'
    UseRoute53Boolean: 'false'
    UseSessionCacheBoolean: 'true'
    WebAsgMax: 4
    WebInstanceType: c5.xlarge
  regions: # List of AWS regions
    - us-west-2
  # Name of S3 bucket to upload project to
  s3_bucket: cat-ccle-aws-refarch-moodle
  # ACL for uploaded s3 objects, defaults to 'private'
  s3_object_acl: public-read
  tags:  # Tags to apply to CloudFormation template
    MyTagKey: ccle-dr
  # Path to template file relative to the project config file path. If
  # defined, template is optional in tests
  template: ./templates/00-master.yaml
tests:  # Test definition section
  my-test:
    # Parameter key-values to pass to CloudFormation, override parameters
    # provided in project section
    parameters:
      ApplicationCacheNodeType: cache.t3.micro
      DatabaseInstanceType: db.t3.micro
      EfsGrowthInstanceType: t3.micro
      UseSessionCacheBoolean: 'false'
      WebAsgMax: 1
      WebInstanceType: t3.micro
    # List of AWS regions, will override any regions defined in project
    regions:
      - us-west-2
    s3_bucket: cat-ccle-aws-refarch-moodle-test
    tags:  # Tags to apply to CloudFormation template
      MyTagKey: ccle-dr-test