project:
  name: aws-refarch-moodle
  owner: quickstart-eng@amazon.com
  regions:
  - us-east-2
  s3_bucket: moodle-templates
  template: templates/00-master.yaml
  parameters:
    QSS3BucketName: 'moodle-templates'
    QSS3BucketRegion: 'us-east-2'
    QSS3KeyPrefix: 'aws-refarch-moodle/'
    BastionInstanceType: t2.nano
    CachePrefix: 'ccle'
    CloudFrontAcmCertificate: ''
    DatabaseCmk: 'arn:aws:kms:us-east-2:897664914431:key/4f7b1258-ae52-4152-8f9e-8e9927cea2be'
    DatabaseEncrpytedBoolean: 'true'
    DatabaseInstanceType: 'db.r4.large'
    DomainName: 'staging.lms.sharepointoscar.com'
    EC2KeyName: moodle_bastion
    EfsCmk: 'arn:aws:kms:us-east-2:897664914431:key/4f7b1258-ae52-4152-8f9e-8e9927cea2be'
    EfsEncrpytedBoolean: 'true'
    SshAccessCidr: 0.0.0.0/0
    HostedZoneName: 'lms.sharepointoscar.com'
    NumberOfAZs: 2
    PublicAlbAcmCertificate: 'arn:aws:acm:us-east-2:897664914431:certificate/3f3c7a36-61b5-4a09-8338-f05d3b3b4b27'
    VpcId: 'vpc-02e8a3a39219fff28'
    PrivateSubnets: subnet-0b10052227f40754f,subnet-05bb8a5e8d03cfbf7
    PublicSubnets: subnet-02348cff86f11fc87,subnet-0e4ac7cc5c2173ec8
    UseRoute53Boolean: 'true'
    UseApplicationCacheBoolean: 'false'
    UseCloudFrontBoolean: 'false'
    UseSessionCacheBoolean: 'false'
    WebAsgMax: 2
    WebAsgMin: 2
    WebInstanceType: t2.xlarge
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      QSS3BucketName: 'moodle-templates'
      QSS3BucketRegion: 'us-east-2'
      QSS3KeyPrefix: 'aws-refarch-moodle/'
    regions:
      - us-east-2