---
AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Moodle on AWS - Creates New VPC

Metadata:
  LintSpellExclude:
    - Kubernetes
    - ARNs
    - Resource Names
    - autoscaler
    - IOPS
    - EfsStorageClass
    - dcd
    - vpc-0343606e
    - Lambda
    - maxIO
  AWS::CloudFormation::Interface:

    ParameterGroups:
    - Label:
        default: Amazon VPC Parameters
      Parameters:
      - VpcId
      - PublicSubnets
      - PrivateSubnets
    ParameterLabels:
      VpcId:
        default: VPC ID
      PublicSubnets:
        default: Public Subnets
      PrivateSubnets:
        default: Private Subnets

Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Select an existing VPC
    Default: ""
  PrivateSubnets:
    Description: Private Subnet List
    Type: List<AWS::EC2::Subnet::Id>
  PublicSubnets:
    Description: Public Subnet List
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  ExistingVPC:
    Type: AWS::EC2::VPC

Outputs:

  Vpc:
    Value: !Ref VpcId
  PublicSubnets:
       Value: !Join [ ',',!Ref PublicSubnets ]
  PrivateSubnets:
     Value: !Join [ ',',!Ref PrivateSubnets ]
