---
AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Moodle on AWS - Creates New VPC

Metadata:
  LintSpellExclude:
    - Kubernetes
    - ARNs
    - Resource Names
    - autoscaler
    - IOPS
    - EfsStorageClass
    - dcd
    - vpc-0343606e
    - Lambda
    - maxIO
  AWS::CloudFormation::Interface:

    ParameterGroups:
    - Label:
        default: Amazon VPC Parameters
      Parameters:
      - VpcId
      - NumberOfAZs
      - AvailabilityZones
      - VpcTenancy
      - PublicSubnets
      - PrivateSubnets
    ParameterLabels:
      VpcId:
        default: VPC ID
      AvailabilityZones:
        default: Availability Zones
      NumberOfAZs:
        default: Number of Availability Zones
      VpcTenancy:
        default: VpcTenancy
      PublicSubnets:
        default: Public Subnets
      PrivateSubnets:
        default: Private Subnets

Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: Select an existing VPC
    Default: ""
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note:
      The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  NumberOfAZs:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 2
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: Number
  VpcTenancy:
    AllowedValues:
    - default
    - dedicated
    Default: default
    Description: The allowed tenancy of instances launched into the VPC
    Type: String
  PrivateSubnets:
    Description: Private Subnet List
    Type: List<AWS::EC2::Subnet::Id>
  PublicSubnets:
    Description: Public Subnet List
    Type: List<AWS::EC2::Subnet::Id>

Conditions:

  NumberOfAZs:
      !Equals [ '1', !Ref NumberOfAZs ]
  NumberOfAZs:
      !Equals [ '2', !Ref NumberOfAZs ]
  NumberOfAZs:
      !Equals [ '3', !Ref NumberOfAZs ]
  NumberOfAZs:
      !Equals [ '4', !Ref NumberOfAZs ]
  NumberOfAZs:
      !Equals [ '5', !Ref NumberOfAZs ]
  NumberOfAZs:
      !Equals [ '6', !Ref NumberOfAZs ]

Resources:

  ExistingVPC: 
    Type: AWS::EC2::VPC

Outputs:
  
  Vpc:
    Value: !Ref VpcId
  PublicSubnets:
       Value: !Join [ ',',!Ref PublicSubnets ]
  PrivateSubnets:
     Value: !Join [ ',',!Ref PrivateSubnets ]
  VpcTenancy:
    Value: !Ref VpcTenancy
  NumberOfAZs:
     Value: !Ref NumberOfAZs
